### PR TITLE
1.5.0.221003 Version Update

### PR DESCRIPTION
**Pull request by psteyer**
Updated from `1.4.4.220912` -> `1.5.0.221003`

Related to old PR: https://github.com/AnacondaRecipes/pandas-stubs-feedstock/pull/2

### CODE REVIEW

**Comment by katietz** [comment]
could you please add changelog to global info block, and point out what changed here in this version?

**Review by varlackc — COMMENTED** [review]
We need to add the `license_family`

https://github.com/AnacondaRecipes/pandas-stubs-feedstock/blob/20954d96554dfc619e46132b50a347ce1f98b4cd/recipe/meta.yaml#L37&L40

**Comment by psteyer** [comment]
> could you please add changelog to global info block, and point out what changed here in this version?
@katietz 

I was unable to find a change log from the upstream repo, but here are the most recent commits for current version and the recent version.

Here are the changes for the most recent version:  https://github.com/pandas-dev/pandas-stubs/commits/v1.5.0.221003

Here are the changes for the previous version: https://github.com/pandas-dev/pandas-stubs/commits/v1.5.0.220926

**Comment by cbouss** [comment]
> > could you please add changelog to global info block, and point out what changed here in this version?
> > @katietz
> 
> I was unable to find a change log from the upstream repo, but here are the most recent commits for current version and the recent version.
> 
> Here are the changes for the most recent version: https://github.com/pandas-dev/pandas-stubs/commits/v1.5.0.221003
> 
> Here are the changes for the previous version: https://github.com/pandas-dev/pandas-stubs/commits/v1.5.0.220926

On any github project you can go to the compare page:
https://github.com/pandas-dev/pandas-stubs/compare/
From there you can select the current version we have and the version you are updating.
https://github.com/pandas-dev/pandas-stubs/compare/v1.4.4.220912...v1.5.0.221003

**Review by cbouss — APPROVED** [review]
LGTM

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
